server:
  port: 8444
  ssl:
    bundle: "self"

spring:
  application:
    name: tls-hot-reload-client
  ssl:
    bundle:
      pem:
        self:
          key:
            alias: "self"
          keystore:
            private-key: "file:/Users/natarajmb/Development/work/java/tls-hot-reload/certs/client.key"
            certificate: "file:/Users/natarajmb/Development/work/java/tls-hot-reload/certs/client.crt"
          reload-on-update: true
        remote:
          key:
            alias: "remote"
          truststore:
            certificate: "file:/Users/natarajmb/Development/work/java/tls-hot-reload/certs/server.crt"
          reload-on-update: true

# Actuator configuration for SSL bundle management
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  server:
    port: 8081
    ssl:
      enabled: false

# Logging configuration
logging:
  level:
    org.springframework.boot.ssl: DEBUG
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: DEBUG

remote:
  url: "https://localhost:8443"