#!/bin/bash
SPRING_SSL_BUNDLE_PEM_SELF_KEYSTORE_PRIVATE_KEY="${SERVER_PRIVATE_KEY}" \
SPRING_SSL_BUNDLE_PEM_SELF_KEYSTORE_CERTIFICATE="${SERVER_CERTIFICATE}" \
SPRING_SSL_BUNDLE_PEM_REMOTE_TRUSTSTORE_CERTIFICATE="${SERVER_TRUSTSTORE_CERTIFICATE}" \
./mvnw spring-boot:run