#!/bin/bash
SPRING_SSL_BUNDLE_PEM_SELF_KEYSTORE_PRIVATE_KEY="${CLIENT_PRIVATE_KEY}" \
SPRING_SSL_BUNDLE_PEM_SELF_KEYSTORE_CERTIFICATE="${CLIENT_CERTIFICATE}" \
SPRING_SSL_BUNDLE_PEM_REMOTE_TRUSTSTORE_CERTIFICATE="${CLIENT_TRUSTSTORE_CERTIFICATE}" \
SPRING_PROFILES_ACTIVE=client ./mvnw spring-boot:run